<a href="https://colab.research.google.com/github/sebavergarasassi/Bussines_Managment/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ing. Vergara Sassi J. Sebastián
* 17/06/23
* Class lines

# In this notebook, we are going to cover some of the most important concepts of tensors using TensorFlow

More specifically, we are going to cover :

  * Introduction to tensors
  * Getting imformation from tensors
  * Using @tf.function ( a way to speed up yout regular Python function)
  * Using GPUs with TensorFlow (or TPUs)

# Introduction to Tensors


In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# Create  tensor with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tenor (ndim stands for number of dimesions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Create a matrix (has more than 1 dimension)
matrix=tf.constant([[10, 7],
                    [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                               [3.,2.],
                               [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
# number of dimesion of another_matrix
another_matrix.ndim

2

In [13]:
# Let's Create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

# what we have created?

  * Scalar: a single number
  * Vector: a number with directions (for example velocity, aceleratios, etc.)
  * Matrix: a 2-dimensional array of numbers
  * Tensor: an n-dimesional array of numbers ( when n can be any number, a 0-dimensional tensor is a scalar , a 1-dimesion tensor is a vector)
